export const translations = {
  da: {
    nav: ["Info", "Galleri", "Om os"],
    eyebrow: "Aalborg siden 2005",
    hero_line1: "Klippe",
    hero_line2: "Huset",
    hero_sub: "Frisørsalon i hjertet af Aalborg",
    book_btn: "Book en tid",
    scroll_hint: "Rul ned",
    prices_label: "Priser",
    men: "Herrer",
    children: "Børn",
    hours_label: "Åbningstider",
    weekday: "Man – Fre",
    saturday: "Lørdag",
    contact_label: "Kontakt",
    address: "Niels Ebbesensgade 15",
    gallery_label: "Galleri",
    about_label: "Om os",
    owner_title: "Ejer & Frisør",
    about_text:
      "Mit navn er Hafizullah Mir og jeg er ejeren og frisøren af Klippe Huset i Aalborg. Jeg er uddannet frisør og startede ud med, at arbejde ved andre frisørsaloner, for at udvide mine kompetencer. I 2005 tog jeg så skridtet og blev selvstændig, hvilket jeg er utrolig glad for i dag.",
    about_text2:
      "Mine værdier ligger i at kunne levere en høj kvalitet som også er prisvenlig. Den bedste følelse for mig er, at kunne skabe et look som klienten ønsker.",
    reviews_label: "Anmeldelser",
    find_us_label: "Find os",
    footer_rights: "Alle rettigheder forbeholdes",
    gallery_title: "Vores",
    gallery_em: "arbejde",
    reviews_title: "Hvad kunder",
    reviews_em: "siger",
    map_title: "Find",
    map_em: "os",
  },
  en: {
    nav: ["Info", "Gallery", "About"],
    eyebrow: "Aalborg since 2005",
    hero_line1: "Klippe",
    hero_line2: "Huset",
    hero_sub: "Hair salon in the heart of Aalborg",
    book_btn: "Book appointment",
    scroll_hint: "Scroll",
    prices_label: "Prices",
    men: "Men",
    children: "Children",
    hours_label: "Opening hours",
    weekday: "Mon – Fri",
    saturday: "Saturday",
    contact_label: "Contact",
    address: "Niels Ebbesensgade 15",
    gallery_label: "Gallery",
    about_label: "About",
    owner_title: "Owner & Hairdresser",
    about_text:
      "My name is Hafizullah Mir and I am the owner and hairdresser of Klippe Huset in Aalborg. I started out working at other salons to expand my skills, and in 2005 I took the step and became self-employed.",
    about_text2:
      "My values lie in delivering high quality that is also affordable. The best feeling for me is creating a look the client truly wants.",
    reviews_label: "Reviews",
    find_us_label: "Find us",
    footer_rights: "All rights reserved",
    gallery_title: "Our",
    gallery_em: "work",
    reviews_title: "What clients",
    reviews_em: "say",
    map_title: "Find",
    map_em: "us",
  },
};

export const reviews = [
  { name: "Rasmus Kastbjerg Hansen", stars: 5, text: "Altid en fornøjelse at komme her. Har brugt Klippe Huset igennem flere år. Dygtige mennesker og altid en rar stemning." },
  { name: "Christian Hoirup", stars: 5, text: "Hafizullah Mir er en professionel frisør, der yder et fantastisk stykke arbejde hver eneste gang. Jeg er blevet klippet hos ham i mange år nu og er altid tilfreds med min frisure, når jeg går derfra. Desuden er prisen god, og du får en gratis klipning hver 8. gang." },
  { name: "Peter Hagn-Meincke", stars: 5, text: "Super god service og Hafiz klipper rigtig godt med både maskine og saks. Jeg har prøvet mange af Aalborg's frisører og dette er helt på højde med de bedste. De varmeste anbefalinger herfra." },
  { name: "Markus Heinesen", stars: 5, text: "Hafiz er meget dygtig – skarp fade hver gang!" },
  { name: "Peter Grandjean", stars: 4, text: "Fin service. Kan næsten altid blive klippet uden lang ventetid og uden tidsbestilling eller med tidsbestilling." },
  { name: "Wail Mohamed", stars: 4, text: "Altid fin behandling. Men prisen er steget meget de senere år, derfor kun 4 stjerner." },
  { name: "J. S.", stars: 4, text: "Fantastisk betjening OK arbejde." },
  { name: "A. P.", stars: 5, text: "Salonen/barberen havde den bedste kvalitet af stil til prisen. Jeg har meget små krøllede hår, mine sædvanlige klipninger består af Cesar's, Dark Caesars, medium og high fades. De herrer, der klippede mit hår, var meget venlige, og han gav gode råd om at style og holde sundt friskt hår." },
  { name: "A. P.", stars: 5, text: "Meget gode, eksperter og venlige barberere, især manden." },
  { name: "P. B.", stars: 5, text: "Virkelig god service! Jeg fik min søn på 4 år klippet og kvinden var meget tålmodig. Min søn gik ud med flot hår. Jeg kan anbefale det!" },
  { name: "W. M.", stars: 5, text: "Jeg lover dig han for dig til at se lækker ud. Fremragende klipning og de er virkelig flinke. Du for enda gratis slik og det smager fantastisk." },
  { name: "O. C.", stars: 5, text: "Hurtig og god klipning uden en masse snak." },
  { name: "F. B.", stars: 5, text: "Det er altid en god oplevelse at blive klippet her. Plus der er venligt og smilende personale der kan bare deres arbejde." },
  { name: "F. P.", stars: 5, text: "Rigtig god service samt super sød folk." },
  { name: "L. W.", stars: 5, text: "Den bebeds frisør i Aalborg 👍 Rigtig god til sit arbejde med stil og kvalitet 💯" },
  { name: "B. U.", stars: 5, text: "Den bedste frisør i Nordjylland.. Mandeklip!" },
  { name: "D. D.", stars: 5, text: "Verdens bedste frisør Hafis 😁" },
  { name: "H. A. K.", stars: 5, text: "Bedste frisør i hele Aalborg." },
  { name: "J. O.", stars: 5, text: "Hyggelig stemning og kompetent klipning." },
  { name: "N. B.", stars: 5, text: "Et godt sted med professionel frisører." },
  { name: "V. N.", stars: 5, text: "Bedste frisør til afro hår i Aalborg 😊" },
  { name: "A. L.", stars: 5, text: "Super klipning til en god pris." },
  { name: "J. K.", stars: 5, text: "God betjening og gode frisører." },
  { name: "H. O. S.", stars: 5, text: "Super pris og service." },
  { name: "U. N.", stars: 5, text: "Kompetent og venlig service 😊" },
  { name: "M. O.", stars: 5, text: "Pisse dygtig frisør 😊" },
  { name: "S. C.", stars: 5, text: "Rigtig søde og dygtige." },
  { name: "O. Y.", stars: 5, text: "Dygtig." },
  { name: "M.", stars: 5, text: "Flot klipning." },
  { name: "S. J.", stars: 5, text: "Bedste frisør i byen." },
  { name: "B. L.", stars: 5, text: "Perfekt." },
  { name: "M. A.", stars: 5, text: "Klasse!!" },
  { name: "i. s.", stars: 5, text: "Aalborgs bedste!!!!" },
  { name: "w. a.", stars: 5, text: "Rigtig god." },
  { name: "U. K.", stars: 5, text: "Den bedste frisør denne by nogensinde har haft!" },
  { name: "V. P.", stars: 5, text: "Rigtig god frisør." },
  { name: "s.", stars: 5, text: "Dejlige mennesker, god hørelse.. jeg er smuk :)" },
  { name: "h. a.", stars: 5, text: "Han mestrer alle klipninger og er meget sød ved kunderne." },
  { name: "A. R.", stars: 5, text: "Meget professionel." },
  { name: "A. N.", stars: 5, text: "Hafiz er den bedste herrefrisør/barber i Aalborg. Uanset pris!" },
  { name: "Morteza Amini", stars: 5, text: "Det er rart at besøge klippe huset, med dygtig betjening og god atmosfære." },
  { name: "Mustafa A.", stars: 5, text: "Husker sine kunder, og er god til at snakke om ting mens man bliver klippet. Han har klippet i flere årtier og er derfor vildt god til at høre og forstå hvad der er man gerne vil have lavet. Derudover er han hurtig, præcis og billig." },
  { name: "Bahiss Afg", stars: 5, text: "Mester til at klippe og lave lige præcis det hår/style man kunne ønske sig.. Og det skal ikke koste meget for godt klipning synes jeg :)" },
  { name: "Anonymous", stars: 5, text: "Kvaliteten af Hafiz' klipning var som sædvanlig perfekt. Jeg kører fra Herning til Aalborg for at blive klippet flere gange om året." },
  { name: "Anonymous", stars: 5, text: "Altid en fornøjelse. Er kommet der igennem 10 år..." },
  { name: "Anonymous", stars: 5, text: "I've been going to this place since I was a small kid, always enjoyed the atmosphere. Nice couches to sit and wait while enjoying candy on the table. The staff is very respectful and always listens to you. I never felt disappointed after an appointment." },
];

export function getDailyReviews(offset = 0) {
  const dayIndex = Math.floor(Date.now() / 86400000) % reviews.length;
  return [0, 1, 2].map((i) => reviews[(dayIndex + offset + i) % reviews.length]);
}
